// App shell: router, sensors bar, coach dock (avatar + chat + voice), and the glue between ears, eyes, voice and views.
import * as store from './store.js';
import { ears } from './audio.js';
import { eyes } from './vision.js';
import { coach } from './coach.js';
import { metronome, strum } from './synth.js';
import { h, $, toast, avatarEl, chordEl, modal } from './ui.js';
import { getShape, prettyChord } from './theory.js';
import { allSongs } from './songs.js';
import { lessonById, ALL_LESSONS } from './lessons.js';
import { VIEWS } from './views.js';
import { describeShape } from './coach.js';

export const app = {
  ctl: null, plan: [], planIdx: -1, current: '', mini: null,
  go(hash) { if (location.hash === hash) render(); else location.hash = hash; },
  async micOn() {
    if (ears.running) return true;
    try { await ears.start(); ears.setSensitivity(store.get().settings.sensitivity); updateSensors(); return true; }
    catch (e) { toast('Microphone blocked. Allow mic access so Axel can hear you.', 'bad', 5000); return false; }
  },
  async camOn(videoEl, canvasEl) {
    try {
      eyes.leftHanded = store.get().profile.leftHanded;
      if (videoEl) await eyes.moveTo(videoEl, canvasEl); else await ensureMiniCam();
      updateSensors(); return true;
    } catch (e) { console.error(e); toast('Camera unavailable: ' + (e.message || e), 'bad', 5000); return false; }
  },
  camOff() { eyes.stop(); app.mini?.remove(); app.mini = null; updateSensors(); },
  startPlan(items) { app.plan = items; app.planIdx = 0; app.go('#/lesson/' + encodeURIComponent(items[0].id)); },
  nextInPlan() {
    if (app.planIdx >= 0 && app.planIdx < app.plan.length - 1) { app.planIdx++; const l = app.plan[app.planIdx]; app.go(l.type === 'link' ? l.href : '#/lesson/' + encodeURIComponent(l.id)); return true; }
    if (app.planIdx === app.plan.length - 1 && app.plan.length) { app.plan = []; app.planIdx = -1; coach.say("That's the session. Great work. Sleep on it; your hands will be better tomorrow."); app.go('#/progress'); return true; }
    return false;
  },
  showChord(sym) {
    const sh = getShape(sym);
    if (!sh) { toast(`No shape for ${sym}`); return `no shape for ${sym}`; }
    strum(sh);
    modal(prettyChord(sym), h('div', { class: 'chord-modal' }, chordEl(sym, { size: 220 }), h('p', {}, describeShape(sym, sh)),
      h('div', { class: 'row' }, h('button', { class: 'btn', onclick: () => strum(sh) }, '▶ Strum'), h('button', { class: 'btn ghost', onclick: () => { document.querySelector('.modal-back')?.remove(); app.go('#/lesson/' + encodeURIComponent('chord:' + sym)); } }, 'Practice it'))));
    return describeShape(sym, sh);
  },
  findSong(q) {
    const songs = allSongs(store.get().userSongs); const s = String(q).toLowerCase();
    return songs.find(x => x.id === q) || songs.find(x => x.title.toLowerCase() === s) || songs.find(x => x.title.toLowerCase().includes(s) || s.includes(x.title.toLowerCase().replace(/\s*\(.*\)/, '')));
  },
  addSong(input, source = 'axel') {
    const id = 'u-' + (input.title || 'song').toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40) + '-' + Date.now().toString(36).slice(-4);
    const s = {
      id, title: input.title, artist: input.artist || 'Unknown', key: input.key || '', capo: input.capo || 0, bpm: input.bpm || 90, meter: input.meter || 4,
      strum: input.strum || 'oldFaithful', sections: input.sections.map(x => ({ name: x.name, bars: x.bars, repeat: x.repeat || 1 })),
      techniques: input.techniques || [], why: input.tips || '', tags: ['mine', source], diff: input.diff || 2,
      source, confidence: input.confidence, verify: source === 'axel' ? `Chart generated by Axel (confidence: ${input.confidence || 'unknown'}). Verify by ear or with the Song Decoder.` : input.verify,
      display: input.display,
    };
    store.get().userSongs.unshift(s); store.save();
    toast(`Added “${s.title}” to your library`, 'good');
    return `added as ${id}`;
  },
};

// ---------- Router ----------
let cleanup = null;
async function render() {
  const [, name = 'home', ...rest] = location.hash.replace(/^#\/?/, '#/').split('/');
  const view = VIEWS[name] || VIEWS.home;
  try { cleanup?.(); } catch (e) { console.error(e); }
  cleanup = null; app.ctl = null;
  if (metronome.running && !['song', 'lesson'].includes(name)) metronome.stop();
  const root = $('#view'); root.innerHTML = ''; root.scrollTop = 0; window.scrollTo(0, 0);
  app.current = name;
  document.querySelectorAll('.nav a').forEach(a => a.classList.toggle('on', a.getAttribute('href') === '#/' + name || (name === 'home' && a.getAttribute('href') === '#/')));
  try { cleanup = await view(root, rest.map(decodeURIComponent), app); }
  catch (e) { console.error(e); root.append(h('div', { class: 'card bad' }, h('h3', {}, 'Something broke on this screen'), h('pre', {}, String(e.stack || e)))); }
  // the mini camera follows you everywhere except the full camera screen
  if (app.mini) app.mini.hidden = name === 'camera';
  if (eyes.running && name !== 'camera' && app.mini && !app.mini.contains(eyes.video)) ensureMiniCam();
}
window.addEventListener('hashchange', render);

// ---------- Sensors bar ----------
const sens = {};
function buildSensors() {
  const bar = $('#sensors');
  sens.mic = h('button', { class: 'sensor', onclick: () => ears.running ? (ears.stop(), updateSensors()) : app.micOn() }, h('i', { class: 'dot' }), h('span', {}, 'Ears'));
  sens.level = h('div', { class: 'lvl' }, h('i'));
  sens.note = h('b', { class: 'heard', title: 'What Axel hears' }, '—');
  sens.cam = h('button', { class: 'sensor', onclick: () => eyes.running ? app.camOff() : app.camOn() }, h('i', { class: 'dot' }), h('span', {}, 'Eyes'));
  sens.voice = h('button', { class: 'sensor', onclick: () => coach.listening ? coach.stopListening() : coach.startListening() }, h('i', { class: 'dot' }), h('span', {}, 'Voice'));
  sens.metro = h('button', { class: 'sensor metro', onclick: () => metronome.running ? metronome.stop() : metronome.start(metronome.bpm) }, h('span', {}, '♩ ', h('b', { class: 'bpm' }, metronome.bpm)));
  const minus = h('button', { class: 'mini-btn', onclick: () => metronome.setBpm(metronome.bpm - 5), 'aria-label': 'Slower' }, '−');
  const plus = h('button', { class: 'mini-btn', onclick: () => metronome.setBpm(metronome.bpm + 5), 'aria-label': 'Faster' }, '+');
  bar.append(sens.mic, sens.level, sens.note, sens.cam, sens.voice, h('div', { class: 'metro-wrap' }, minus, sens.metro, plus));
  metronome.addEventListener('bpm', () => { sens.metro.querySelector('.bpm').textContent = metronome.bpm; });
  metronome.addEventListener('start', updateSensors); metronome.addEventListener('stop', updateSensors);
  metronome.addEventListener('beat', e => { sens.metro.classList.add('tick'); setTimeout(() => sens.metro.classList.remove('tick'), 90); if (e.detail.beatInBar === 0) sens.metro.classList.add('down'); else sens.metro.classList.remove('down'); });
  coach.addEventListener('listening', updateSensors);
  ears.addEventListener('frame', () => {
    sens.level.firstChild.style.width = Math.min(100, Math.max(0, (ears.db + 60) * 1.8)) + '%';
    const c = ears.chord, p = ears.pitch;
    const txt = c && c.score > 0.8 ? prettyChord(c.name) : p ? noteLabel(p.note) : '—';
    if (sens.note.textContent !== txt) sens.note.textContent = txt;
  });
}
const noteLabel = m => ['C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B'][m % 12] + (Math.floor(m / 12) - 1);
function updateSensors() {
  sens.mic.classList.toggle('on', ears.running);
  sens.cam.classList.toggle('on', eyes.running);
  sens.voice.classList.toggle('on', coach.listening);
  sens.metro.classList.toggle('on', metronome.running);
}

// Floating mini camera so Axel keeps watching during lessons.
async function ensureMiniCam() {
  if (!app.mini) {
    const v = h('video', { playsinline: true, muted: true }), c = h('canvas');
    app.mini = h('div', { class: 'mini-cam', title: 'Axel is watching your hands' }, v, c, h('button', { class: 'icon-btn', onclick: () => app.camOff(), 'aria-label': 'Turn camera off' }, '✕'));
    document.body.append(app.mini);
  }
  const v = app.mini.querySelector('video'), c = app.mini.querySelector('canvas');
  await eyes.moveTo(v, c);
}

// ---------- Coach dock ----------
let avatar;
function buildDock() {
  const dock = $('#dock');
  avatar = avatarEl(76);
  const bubble = h('div', { class: 'bubble', 'aria-live': 'polite' }, 'Yo! I\'m Axel. Turn on my Ears 🎤 and Eyes 📷 up top, then hit Start.');
  const heard = h('div', { class: 'heard-line' });
  const input = h('input', { type: 'text', placeholder: 'Ask Axel… (or say "Axel, show me F")', 'aria-label': 'Message Axel' });
  const send = () => { const v = input.value.trim(); if (!v) return; input.value = ''; coach.ask(v); };
  input.addEventListener('keydown', e => { if (e.key === 'Enter') send(); });
  const talk = h('button', { class: 'talk', title: 'Push to talk', 'aria-label': 'Push to talk', onclick: () => coach.pushToTalk() }, '🎙');
  const hush = h('button', { class: 'icon-btn', title: 'Stop talking', 'aria-label': 'Stop Axel talking', onclick: () => coach.stopSpeaking() }, '■');
  const toggle = h('button', { class: 'icon-btn collapse', 'aria-label': 'Collapse coach', onclick: () => dock.classList.toggle('collapsed') }, '▾');
  dock.append(h('div', { class: 'dock-face', onclick: () => dock.classList.remove('collapsed') }, avatar.el), h('div', { class: 'dock-main' }, bubble, heard, h('div', { class: 'dock-input' }, input, talk, hush)), toggle);
  coach.addEventListener('reply', e => { bubble.textContent = e.detail.text; bubble.classList.remove('user'); });
  coach.addEventListener('said', e => { bubble.textContent = e.detail; bubble.classList.remove('user'); });
  coach.addEventListener('user', e => { heard.textContent = '🗣 ' + e.detail; });
  coach.addEventListener('hearing', e => { heard.textContent = (e.detail.final ? '🗣 ' : '… ') + e.detail.text; });
  coach.addEventListener('armed', () => { heard.textContent = '👂 Listening…'; avatar.listening(true); setTimeout(() => avatar.listening(coach.listening), 4000); });
  coach.addEventListener('note', e => toast(e.detail, 'info', 5000));
  coach.addEventListener('speaking', e => avatar.speaking(e.detail));
  coach.addEventListener('syllable', () => avatar.syllable());
  coach.addEventListener('listening', e => avatar.listening(e.detail));
  // Eyes follow your hands (or the mouse when the camera is off)
  eyes.addEventListener('frame', () => { const g = eyes.gazeTarget(); avatar._tracking = !!g; if (g) avatar.look((g.x - 0.6) * 2.2, (g.y - 0.3) * 1.8); });
  document.addEventListener('pointermove', e => { if (eyes.running) return; const r = avatar.el.getBoundingClientRect(); avatar._tracking = true; avatar.look((e.clientX - r.left - r.width / 2) / 300, (e.clientY - r.top - r.height / 2) / 300); clearTimeout(app._mt); app._mt = setTimeout(() => { avatar._tracking = false; }, 1500); });
  eyes.addEventListener('gesture', e => {
    if (e.detail === 'thumbsup') { avatar.mood('happy'); toast('👍 Next!', 'good', 1200); coach.actions.next(); }
    if (e.detail === 'palm') { toast('✋ Stop', 'info', 1200); coach.actions.stop(); }
  });
  app.avatar = avatar;
  if (window.matchMedia('(max-width: 860px)').matches) dock.classList.add('collapsed');
  coach.addEventListener('said', () => dock.classList.remove('collapsed'), { once: true });
}
export const celebrate = () => avatar?.mood('happy');

// ---------- Coach wiring ----------
coach.actions = {
  navigate: v => app.go('#/' + (v === 'home' ? '' : v)),
  showChord: s => app.showChord(s),
  startLesson: id => { const l = lessonById(id) || ALL_LESSONS.find(x => x.id.toLowerCase() === id.toLowerCase()); if (!l) return 'unknown lesson; ids look like chord:G, change:G-C, strum:oldFaithful, song:<song id>'; app.go('#/lesson/' + encodeURIComponent(l.id)); return 'started ' + l.title; },
  openSong: q => { const s = app.findSong(q); if (!s) return 'not in library'; app.go('#/song/' + encodeURIComponent(s.id)); return 'opened ' + s.title; },
  metronome: ({ bpm, on }) => { if (bpm) metronome.setBpm(bpm); if (on === false) metronome.stop(); else if (on) metronome.start(metronome.bpm); },
  addSong: input => app.addSong(input, 'axel'),
  next: () => app.ctl?.next?.() ?? (app.nextInPlan() || null),
  back: () => history.back(),
  repeat: () => app.ctl?.repeat?.(),
  tempo: f => { if (app.ctl?.tempo) app.ctl.tempo(f); else metronome.setBpm(metronome.bpm * (1 + f)); coach.say(`${metronome.bpm} bpm.`); },
  stop: () => { app.ctl?.stop?.(); metronome.stop(); },
  start: () => app.ctl?.start?.(),
};
coach.context = () => {
  const st = store.get();
  return {
    screen: app.current, hash: location.hash,
    ears: ears.running ? { heardChord: ears.chord?.score > 0.75 ? ears.chord.name : null, heardNote: ears.pitch ? noteLabel(ears.pitch.note) : null, centsOff: ears.pitch ? Math.round(ears.pitch.cents) : null, levelDb: Math.round(ears.db || -90) } : 'off',
    eyes: eyes.running ? { fretHandVisible: !!eyes.fret, strumHandVisible: !!eyes.strum, postureScore: eyes.posture?.score, flatFingers: eyes.posture?.flat, wristBend: eyes.posture ? Math.round(eyes.posture.wristBend) : null, strokesPerMin: eyes.strumRate() } : 'off',
    metronome: { on: metronome.running, bpm: metronome.bpm },
    lesson: app.ctl?.describe?.() || null,
    student: { name: st.profile.name, goal: st.profile.goal, streakDays: st.streak.count, stage: st.stage, chordsKnown: Object.entries(st.skills).filter(([k, v]) => k.startsWith('chord:') && v.level >= 2).map(([k]) => k.slice(6)), bests: st.bests, favorites: st.profile.favorites },
  };
};

// ---------- Boot ----------
function boot() {
  buildSensors(); buildDock(); updateSensors();
  const st = store.get();
  if (st.settings.gateDb) ears.gateDb = st.settings.gateDb;
  metronome.volume = st.settings.metronomeVol;
  if (st.profile.name) $('#hello').textContent = st.profile.name;
  render();
  // Unlock audio on first gesture (autoplay policies)
  window.addEventListener('pointerdown', () => ears.ensureContext(), { once: true });
  if (!st.seen.welcome) {
    st.seen.welcome = 1; store.save();
    setTimeout(() => coach.say("Hey, I'm Axel, your guitar coach. I can hear you, I can see your hands, and I'll get you playing songs you love fast. Hit Start Today's Session when you're ready."), 900);
  }
  let t0 = Date.now();
  setInterval(() => { if (document.visibilityState === 'visible' && (ears.running || metronome.running)) { const m = (Date.now() - t0) / 60000; if (m >= 1) { store.logMinutes(1); t0 = Date.now(); } } else t0 = Date.now(); }, 15000);
}
boot();
